version: '3.8'
services:
  voice-translator:
    build: .
    ports:
      - "80:80"
      - "5000:5000" 
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./temp:/app/temp